### ISSUE TITLE
Calculator meta-analysis:

### ISSUE THREAD

**Issue by tanho63** [dynastyprocess/apps#4]
- [x] Add scheduled write to DP server

Research Questions:
- [ ] - Who are the most popular players? (over a specific timeframe)
- [ ] - What does the distribution of percentage differences look like for all users?
- [ ] - What is the distribution of percentage difference for a (few) players? (allocating proportionately based on value ofc)
- [ ] - What is the distribution of "league-sizes"?
- [ ] - What is the distribution of "valuation factors"?
- [ ] - What is the distribution of "rookie optimism"?
- [ ] - What is the distribution of "future-factor"?
